export const SCREENS = {
  APP_MENU: 'APP_MENU',
  LOGIN: 'LOGIN',
  CHAT: 'CHAT',
  ACCOUNT: 'ACCOUNT',
  SETTINGS: 'SETTINGS',
  SETTINGS_MESSAGE: 'SETTINGS_MESSAGE',
  WEBVIEW: 'WEBVIEW',
  NO_URL: 'NO_URL',
  CHANNELS_MANAGEMENT: 'CHANNELS_MANAGEMENT',
  CHANNELS_LIST: 'CHANNELS_LIST'
};