module.exports = {
  preset: 'react-native',
  setupFilesAfterEnv: ['./jest.setup.js'],
  transformIgnorePatterns: [
    'node_modules/(?!(jest-)?@?react-native|@react-native-community|@react-navigation|@expo|expo-.*)'
  ],
  moduleFileExtensions: ['ts', 'tsx', 'js', 'jsx'],
  collectCoverage: true,
  collectCoverageFrom: [
    '**/*.{js,jsx}',
    '!**/coverage/**',
    '!**/node_modules/**',
    '!**/babel.config.js',
    '!**/jest.setup.js',
  ],
  moduleNameMapper: {
    '^@/(.*)$': '<rootDir>/$1',
    '^expo-notifications$': '<rootDir>/jest/mocks/expo-notifications.js'
  },
  testEnvironment: 'jsdom',
  testMatch: ['**/__tests__/**/*.test.js'],
  coveragePathIgnorePatterns: [
    '/node_modules/',
    '/__tests__/',
    '/__mocks__/',
    'jest.config.js',
    'react-native.config.js',
    '.eslintrc.js',
    'babel.config.js',
    'eas.json',
    'app.json',
    'LeancureApp/i18n/translations/',
    'LeancureApp/plugins/',
    'LeancureApp/i18n/index.js',
    'env.js',
    'firebase.js',
    'ErrorBoundary.js',
    'LeancureApp/services/notification',
    'ScreenSaver.js',
    'NoUrlScreen.js',
    'CommonSettings.js',
    'UseDeviceType.js',
    'UseWebview.js',
    'useWebSocket.js',
    'WebviewScreen.js',
    'LeancureApp/screens/common',
    'Login.js',
    'ChatWindow.js',
    'Login.js',
  ],
};