module.exports = {
  preset: 'jest-expo',
  setupFilesAfterEnv: ['<rootDir>/jest.setup.js'],
  transformIgnorePatterns: [
    'node_modules/(?!((jest-)?react-native|@react-native(-community)?)|expo(nent)?|@expo(nent)?/.*|@expo-google-fonts/.*|react-navigation|@react-navigation/.*|@unimodules/.*|unimodules|sentry-expo|native-base|react-native-svg)',
  ],
  moduleFileExtensions: ['ts', 'tsx', 'js', 'jsx'],
  collectCoverage: true,
  collectCoverageFrom: [
    '**/*.{js,jsx}',
    '!**/coverage/**',
    '!**/node_modules/**',
    '!**/babel.config.js',
    '!**/jest.setup.js',
  ],
  moduleNameMapper: {
    '^@/(.*)$': '<rootDir>/$1',
  },
  testEnvironment: 'node',
  testMatch: ['**/__tests__/**/*.test.js'],
  coveragePathIgnorePatterns: [
    '/node_modules/',
    '/__tests__/',
    '/__mocks__/',
    'jest.config.js',
    'react-native.config.js',
    '.eslintrc.js',
    'babel.config.js',
    'eas.json',
    'app.json',
    'LeancureApp/i18n/translations/',
    'LeancureApp/plugins/',
    'LeancureApp/i18n/index.js',
    'env.js',
    'firebase.js',
    'ErrorBoundary.js',
    'LeancureApp/services/notification',
    'ScreenSaver.js',
    'NoUrlScreen.js',
    'CommonSettings.js',
    'UseDeviceType.js',
    'UseWebview.js',
    'useWebSocket.js',
    'WebviewScreen.js',
    'LeancureApp/screens/common',
  ],
};