name: CI Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.17.0'
      - name: Install dependencies
        run: npm install
      - name: Run linting
        run: npm run lint

  test:
    needs: lint
    runs-on: ubuntu-latest
    steps:
      # We check out the code
      - uses: actions/checkout@v3
      # We setup the Node.js environment
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.17.0'
      # We install the dependencies
      - name: Install dependencies
        run: |
          npm install
          npm install --save-dev jest @testing-library/react-native @testing-library/jest-native jest-expo react-test-renderer@18.2.0
      - name: Run unit tests
        env:
          NODE_OPTIONS: "--max-old-space-size=4096"
        run: npm run test
      # We upload the coverage reports
      - name: Upload coverage reports
        uses: codecov/codecov-action@v3